site: Bryan Portfolio

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /photography/:slug
  projects:
    output: true
    permalink: /portfolio/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 4
paginate_path: "/portfolio/page:num/"